const express = require("express");
const router = express.Router();
const adminController = require("../controllers/adminController");
const adminHmacAuth = require("../middleware/adminHmacAuth");
const metricsController = require("../controllers/metricsController");
const reportController = require("../controllers/reportController");
const reconciliationController = require("../controllers/reconciliationController");

router.get("/players", adminHmacAuth, adminController.getPlayers);
router.get("/wallets", adminHmacAuth, adminController.getWallets);
router.get("/games", adminHmacAuth, adminController.getGames);
router.post("/games", adminHmacAuth, adminController.createGame);
router.get("/games/:id", adminHmacAuth, adminController.getGame);
router.patch("/games/:id", adminHmacAuth, adminController.updateGame);
router.get("/metrics/summary", adminHmacAuth, metricsController.getSummary);
router.get("/reports/ggr", adminHmacAuth, reportController.getGgrReport);
router.get("/reports/transactions.csv", adminHmacAuth, reportController.exportTransactionsCsv);
router.get("/reconciliation/rounds", adminHmacAuth, reconciliationController.listRounds);
router.get("/reconciliation/discrepancies", adminHmacAuth, reconciliationController.listDiscrepancies);
router.get("/reconciliation/export.csv", adminHmacAuth, reconciliationController.exportRoundsCsv);
router.get("/reconciliation/rtp-summary", adminHmacAuth, reconciliationController.getRtpDeviationSummary);
router.get("/rtp/global", adminHmacAuth, adminController.getGlobalRtp);
router.post("/rtp/global", adminHmacAuth, adminController.updateGlobalRtp);
router.get("/rtp/logs", adminHmacAuth, adminController.listRtpLogs);

router.get("/tenants", adminHmacAuth, adminController.getTenants);
router.post("/tenants", adminHmacAuth, adminController.createTenant);
router.patch("/tenants/:id", adminHmacAuth, adminController.updateTenant);
router.patch("/tenants/:id/status", adminHmacAuth, adminController.updateTenantStatus);
router.delete("/tenants/:id", adminHmacAuth, adminController.deleteTenant);
router.post("/tenants/:id/credentials/rotate", adminHmacAuth, adminController.rotateTenantCredential);
router.get("/tenants/:id/wallet-config", adminHmacAuth, adminController.getTenantWalletConfig);
router.post("/tenants/:id/wallet-config", adminHmacAuth, adminController.upsertTenantWalletConfig);
router.get("/tenants/:id/ip-allowlist", adminHmacAuth, adminController.listTenantIpAllowlist);
router.post("/tenants/:id/ip-allowlist", adminHmacAuth, adminController.addTenantIpAllowlistEntry);
router.delete("/tenants/:id/ip-allowlist/:entryId", adminHmacAuth, adminController.removeTenantIpAllowlistEntry);
router.get("/tenants/:id/wallet/logs", adminHmacAuth, adminController.getTenantWalletLogs);
router.get("/wallet/logs", adminHmacAuth, adminController.listWalletLogs);
router.get("/wallet/logs/metrics", adminHmacAuth, adminController.getWalletLogMetrics);
router.patch("/tenants/:id/games/:gameId", adminHmacAuth, adminController.updateTenantGame);
router.get("/tenants/:id/users", adminHmacAuth, adminController.listTenantUsers);
router.post("/tenants/:id/users", adminHmacAuth, adminController.createTenantUser);
router.patch("/tenants/:id/users/:userId/status", adminHmacAuth, adminController.updateTenantUserStatus);
router.post("/tenants/:id/users/:userId/password", adminHmacAuth, adminController.resetTenantUserPassword);

module.exports = router;
